### ISSUE TITLE
city_updater_tool todo & fixme

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#10]
FIXME: fix data to be properly posted in a txt file in order to be next updated with city_updater_tool2

IDEAS:
TODO: names of cities in english?
TODO: city updater_tool2 file merged with first one or maybe left alone is better?
TODO: maybe use mysql additionaly
TODO: make the java files run other way than by Eclipse

PROBLEMS:
currently we can only get degrees and minutes but not seconds. I could not locate page that would provide a list of all, only this or degree format calculated from degree, minutes and second. Maybe there is such a way. There are pages that post that info(all three atributes) but separetly as a query of each town. Doing that would require knowledge of how to make a query(send some argument in javascript boxfiled to obtain wanted address) in java. Also this solution would be taking much more time than now as this query operations take much more time that just working on list on one page.

**Comment by kermit10000000** [comment]
FIXME solved
TODO: city updater_tool2 file merged with first one or maybe left alone is better:
we could do this maybe as functions used in one main instead of two separeted main files. What is your opinion @JaroslawWiosna ?

**Comment by kermit10000000** [comment]
New FIXME stopping from delivery: It seems to not see cities on the letter A.
Update: 23:04 03.10.17: solved but not quite. Still missing 2 cities but it is not stopping issue on the first look but some different issue.

**Comment by JaroslawWiosna** [comment]
In general it would be easier to provide 'decimal' latitude and longitude. 
Seconds it is not important right now. To my mind, we can ignore seconds, nevertheless we should implement our code remembering about seconds.
I mean: it the future it should be possible to parse seconds without refactoring the whole project.

I do not have an opinion about udpater_tool2. It is up to you :)

**Comment by kermit10000000** [comment]
update: 
problem of decimal from first comment solved as aggreed in https://github.com/JaroslawWiosna/regionalizer/issues/19
IDEAS:
TODO: names of cities in english? - currently can be also considered closed as current idea is to just remove polish letters, may be reopened in the future
TODO: city updater_tool2 file merged with first one or maybe left alone is better? - my opinion is to leave it for now as the both use different source and functionality so keeping them separed for now will be better for fixing and detecting bugs
TODO: maybe use mysql additionaly - seems pointless at this point as for now we read txt files. maybe added later in the future for fun or if needed for some additional functions
TODO: make the java files run other way than by Eclipse - this idea actually should be done but don't have any idea now how to do this (maybe some tests and/or travis running them?) - but it is additional functionality only when we will have more time.

**Comment by JaroslawWiosna** [comment]
>TODO: names of cities in english? - currently can be also considered closed as current idea is to just remove polish letters, may be reopened in the future

Yes. Let's close it. But #25 is opened as a research task.

>TODO: city updater_tool2 file merged with first one or maybe left alone is better? - my opinion is to leave it for now as the both use different source and functionality so keeping them separed for now will be better for fixing and detecting bugs

I agree.

>TODO: maybe use mysql additionaly - seems pointless at this point as for now we read txt files. maybe added later in the future for fun or if needed for some additional functions

I think we can open an issue for that and keep it in backlog.

>TODO: make the java files run other way than by Eclipse - this idea actually should be done but don't have any idea now how to do this (maybe some tests and/or travis running them?) - but it is additional functionality only when we will have more time.

#26 is opened as a research task.

**Comment by JaroslawWiosna** [comment]
I think, that it's nice to have separate issue for each TODO, or FIXME or whatever.
...it is just easier to track bugs, issues and so on.

Let's create new issue from this thread and close it.

**Comment by kermit10000000** [comment]
Ok sounds good to me.  Since you created separeted issues for the names in english and running java outside eclipse i just created issue for mysql https://github.com/JaroslawWiosna/regionalizer/issues/30 and I am closing this issue
