### ISSUE TITLE
progress bar throws bad alloc

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#105]
#### Description

The issue can be seen in here https://github.com/JaroslawWiosna/regionalizer/pull/100 lines 1321-1323
> terminate called after throwing an instance of 'std::bad_alloc'
> what():  std::bad_alloc
> make: *** [test] Aborted (core dumped)

--- 

#### Release affected

Yes, this bug should be removed before 0.4.0 (and also + working unit test on progress bar after fix)

---

#### Priority

Medium Prio

---

#### Is there possible contributor who could fix the issue

Jaroslaw Wiosna @JaroslawWiosna 

---

**Comment by JaroslawWiosna** [comment]
Starting from scratch with 7e13971
