### ISSUE TITLE
Region unittests

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#107]
#### Description

Region unittests should be made when the task with regio class refactoring will be closed

--- 

#### Release affected

Well... yes. We agreeded that when we deliver code we also deliver unittests so it should be done before v0.4.0

---

#### Priority

Medium as desribed above

---

#### Is there possible contributor who could fix the issue

---

**Comment by kermit10000000** [comment]
@JaroslawWiosna will you do them when you finish the class?

**Comment by JaroslawWiosna** [comment]
As soon as #87 is finished. Give, me two hours.

**Comment by JaroslawWiosna** [comment]
#87 is closed, @kermit10000000

**Comment by kermit10000000** [comment]
i think it was done with https://github.com/JaroslawWiosna/regionalizer/pull/111/commits/9991f0bf00f67d410b5d8a82de896db786bdf8da and previous one. @JaroslawWiosna what is your opinion?

**Comment by JaroslawWiosna** [comment]
Yes, I think it could be closed.
