### ISSUE TITLE
common document

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#11]
common document to track current project tree and current functionality

**Comment by JaroslawWiosna** [comment]
@kermit10000000 let's consider doxygen comments, like
```c++
/**
 * @brief Some description
 *
 * @param [in] std::size_t abc
 * @param [in] double xyz
 *
 * @todo TODO some todo
 * @return Returns something...
 */
```
...before each declaration of function

**Comment by kermit10000000** [comment]
The idea looks fine to me. It will make small parts more clear. Although, I think we also need something to see the big picture as a whole as well.

**Comment by JaroslawWiosna** [comment]
@kermit10000000 looks like we could use [doxygraph](https://stackoverflow.com/a/26859609) 
Since we have already agreed than doxygen comments is necessary, I think this 'doxygraph' thing may by worth trying...

**Comment by kermit10000000** [comment]
Since we already agreeded for this solution i would like to ask you for updating some files in a free time in doxygen comments as I did.
In case of big pictures since we have also agreeded that doxygen will work here too,I have a proposal. My proposition is creating class for handling doxygen linux commands and calling this object methods in main to achieve new doxygen file with every run and keep the created file updated in repo.
For the first part i ask for your replay and in terms of the second part i seek some discussion soon.

**Comment by JaroslawWiosna** [comment]
OK, I am preparing some comments, like in  b0f361d

**Comment by kermit10000000** [comment]
Update about big picture proposition. I have found some commands for running doxygen: http://www.tutorialspoint.com/unix_commands/doxygen.htm . Now i am looking for some specific commands for doxygraph

**Comment by JaroslawWiosna** [comment]
With  8d68daa I have prepared initial doxygen. 
City.hpp is not included in documentation, unfortunately... 
But I will work on it.
Please refer to README. I included mini-tutorial about doxygen.

------

EDIT:
...and about the big picture. I think we should discuss it in person.

**Comment by kermit10000000** [comment]
big picture solved by @JaroslawWiosna  with doxygen documents and graphs(effect for example can be seen in README.md )
