### ISSUE TITLE
database - decision on common format

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#19]
Currently my java code is suporting pulling coordinates in degrees+minutes. Although as we would like to have degrees(where minutes are decimal part of degrees) only version in database we need agreement upon some common format so open issues are:
1. Should the format in database be:
a) degrees + minutes | degrees in decimal
b) degrees in decimal only
2. Should we keep having "N" and "E" letters in coordinates. It is pointless regarding Poland as we are not that big but might be useful in case we would make it for other countries but that would require rebuilding java database_tool anyway in handling multiple links and databases? Do we even support this format right now? 
3. Way of getting values of degrees in decimal. I saw you had some formula and we also know that 60 minutes is one degree. So should we trust this math and just get them by calculating on values from hard coded database that we already have in degrees and minutes? Or maybe we should just get them additionally from some other webpage(more code and we would need trusted source)

**Comment by JaroslawWiosna** [comment]
1. degrees in decimal only is my pick.
I think by default we should have only decimal. Degrees + minutes would be treated as a additional way of setting the values in City constructors. For now we can only support decimal values.
2. No, we do not have to have `N` and `E` letters.
This is not needed at all.
Well, in the future it would be nice to **regionalize** other countries as well, like Argentina or Australia. But this is not our primary objective.
3. I am not sure if I understood you well, but I would trust **this math**. There is no need for double-checking the conversion from degrees+minutes to decimal degrees. 
I think that small errors in conversions are acceptable...

**Comment by kermit10000000** [comment]
Rules from all 3 pointes provided by new java city_udate_tools https://github.com/JaroslawWiosna/regionalizer/pull/23 
Additionally:
- comment containg prepared support for adding directions like "E" for the future implemententions
- cities without polish letters as it was additional agreeded
- added by me rounding precision of decimal degrees set to 4(can be changed if requested)

**Comment by kermit10000000** [comment]
I know it is closed but this information should be placed in Common database as it is important part of common agreement. The database order is:  City name|Area|Population|Latitude|Longitude
