### ISSUE TITLE
Can we use polish letters in modern c++?

### ISSUE THREAD

**Issue by JaroslawWiosna** [JaroslawWiosna/regionalizer#25]
Research task:
**We have to build knowledge about polish letters in modern c++.**
It looks like modern c++ uses unicode:

- [x] ~~Is it possible?~~ Yes, it is. [c++14](https://ideone.com/j0ZQpx)
- [ ] Is it allowed? When? Always?
- [ ] Linux/Windows differences?
- [ ] C++11/14/17 differences

This is low priority task.

**Comment by kermit10000000** [comment]
https://stackoverflow.com/questions/16236266/how-to-output-polish-characters-in-c-console-application
https://stackoverflow.com/questions/402283/stdwstring-vs-stdstring?noredirect=1&lq=1

**Comment by kermit10000000** [comment]
It is not valid any more as we do not need this for our project. Maybe re-opened if we will ever need it.
