### ISSUE TITLE
Update github files

### ISSUE THREAD

**Issue by JaroslawWiosna** [JaroslawWiosna/regionalizer#37]
- [x] update CODE_OF_CONDUCT.md
- [x] update CONTRIBUTING.md
- [x] update ISSUE_TEMPLATE.md

**Comment by kermit10000000** [comment]
can we copy the code_of_conduct from online templates or should we make our own one?

**Comment by JaroslawWiosna** [comment]
@kermit10000000 let's adapt [default code of conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html)
..but I guess only two or three rules we should adapt as our primary rules.
The reason for this is that one should remember it. Keeping it short would help contributors to remember it.

**Comment by kermit10000000** [comment]
Just in spirit of making this file i recall myself one quote(as we all after all are PEOPLE not machines and robots ;) ):
“Sure, in a real world, those who violate the rules and fail to follow orders...are lower than garbage. However...those who do not care for and support their fellows...are even lower than that!"
