### ISSUE TITLE
clean code for namespaces in c++ & java

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#45]
#### Descrpition

clean code for namespaces

--- 

#### Release affected

zero effect for functionality

---

#### Priority

unknown

---

#### Is there possible contributor who could fix the issue

unknown

---

**Comment by JaroslawWiosna** [comment]
@kermit10000000 
If you are talking about indentiation level for namespaces:

```c++
namespace foo {

void bar() {
    int baz{};
}

} // namespace
```
That's OK.

---
Below you can find an example of bad code style:
```c++
namespace foo {
    // THIS LEVEL OF INDENTIATION IS BAD!
   void bar() {
       int baz{};
    }

} // namespace
```

Please, read here: [https://google.github.io/styleguide/cppguide.html#Namespaces](https://google.github.io/styleguide/cppguide.html#Namespaces)

**Comment by kermit10000000** [comment]
Ok, I see now :)
