### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#46]
#### Descrpition

When looking into the files of our regionalizer i saw a lot of TODO messages. If we ignore this problem now it might be growing to a huge level in the future.
I would like to discuss:
1) why there is so many of them?
2) how big impact they have on the code?
3) should we prioritize them?
4) should we document and prioritize them. If yes, in what way? What ruls should we obey?
5) How will we divide the work to solve them?
Not sure if this is to be discussed in comments. Maybe we should add to the agenda of the meeting(that one we were about to make anyway)?
--- 

#### Release affected

To be discussed

---

#### Priority

To be discussed

---

#### Is there possible contributor who could fix the issue

Yes but we must talk it through first.

---

**Comment by kermit10000000** [comment]
@JaroslawWiosna  is this solved by https://github.com/JaroslawWiosna/regionalizer/pull/67/commits/cab340229c0c386318b23c1af714414341923a73 ?

**Comment by JaroslawWiosna** [comment]
@kermit10000000 Yes. I am closing the issue
