### ISSUE TITLE
machine learning - prepare knowledge base in wiki

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#52]
#### Descrpition

machine learning - prepare knowledge base in wiki

--- 

#### Release affected

Yes. It is part of the 0.3.0 release

---

#### Priority

HIGH - because it must be done before 0.3.0

---

#### Is there possible contributor who could fix the issue

Jaroslaw Wiosna and maybe new contributors.

---

**Comment by JaroslawWiosna** [comment]
Here is the place for this on wiki: [click](https://github.com/JaroslawWiosna/regionalizer/wiki/Machine-learning-knowledge-base)

**Comment by JaroslawWiosna** [comment]
More or less.... DONE.
