### ISSUE TITLE
semi-brute-force for two regions and three regions.

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#54]
#### Descrpition

Expanding the current functions with functionality for more regions.

--- 

#### Release affected

Yes. It is part of the 0.3.0 release

---

#### Priority

HIGH - because it must be done before 0.3.0

---

#### Is there possible contributor who could fix the issue

Jaroslaw Wiosna

---

**Comment by JaroslawWiosna** [comment]
Semi - brute force 
...issue considered as done, because of the introduced `regionalize randomly` feature.

Done.
