### ISSUE TITLE
population map in gnuplot as animated gif image

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#55]
#### Descrpition

population map in gnuplot as animated gif image created from multiple of the frames with gnuplot

--- 

#### Release affected

Yes. It is part of the 0.3.0 release

---

#### Priority

HIGH - because it must be done before 0.3.0

---

#### Is there possible contributor who could fix the issue

Jaroslaw Wiosna

---

**Comment by JaroslawWiosna** [comment]
[![https://i.imgur.com/ouBtpZ3.gif](https://i.imgur.com/ouBtpZ3.gif)](https://i.imgur.com/ouBtpZ3.gif)

More or less this is how I want it to look like.

**Comment by JaroslawWiosna** [comment]
[![image](https://media.giphy.com/media/3o7aCR7bNwd8EqMuAM/giphy.gif)](https://media.giphy.com/media/3o7aCR7bNwd8EqMuAM/giphy.gif)

---

Adressed by #71
