### ISSUE TITLE
internationalization

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#56]
#### Descrpition

internationalization for:

    polish
    sweden
    german ... the code so the "translation collaborators" could finally be a part of the project. impact on project... (two parts: a) adjust the code so the po file could be a part of the legacy code, b) then translators could finally work)

--- 

#### Release affected

Yes. It is part of the 0.3.0 release

---

#### Priority

VERY HIGH - because it must be done before 0.3.0 and stoppes other contributors

---

#### Is there possible contributor who could fix the issue

Jaroslaw Wiosna

---

**Comment by JaroslawWiosna** [comment]
The first steps 3814fab and abe92d0
Done.
