### ISSUE TITLE
help.txt should be dropped from the code

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#58]
#### Descrpition

Changes made to the way we use help.txt now.

--- 

#### Release affected

Yes. It is probably part of the 0.3.0 release

---

#### Priority

Medium Prio - it should be part of 0.3.0 reliese but we need to find the contributor

---

#### Is there possible contributor who could fix the issue

Waiting for an offer to participate to be accepted.

---

**Comment by JaroslawWiosna** [comment]
I'm on my way to find the most appropriate developer to take over this issue.

**Comment by JaroslawWiosna** [comment]
Starting from scratch with 7e13971
