### ISSUE TITLE
Enable coveralls

### ISSUE THREAD

**Issue by JaroslawWiosna** [JaroslawWiosna/regionalizer#7]
Enable coveralls

**Comment by kermit10000000** [comment]
adding label bug since it was introducted but did not work correctly

**Comment by JaroslawWiosna** [comment]
@michal915 Do you know how to enable coverity? (lcov in travis is not working: gcda files are not generated)

**Comment by kermit10000000** [comment]
Part of 0.4.0 release.

**Comment by kermit10000000** [comment]
closed by https://github.com/JaroslawWiosna/regionalizer/pull/88#pullrequestreview-74252830
