### ISSUE TITLE
clang-format in travis

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#74]
#### Descrpition

As it was discussed in here: https://github.com/JaroslawWiosna/regionalizer/pull/72#event-1310181870 .
We should introduce clang-format in script but it is not that easy so maybe it will be in another release.

--- 

#### Release affected

If we will find time and decide we can make it in v0.3.0 but possible it is v0.4.0

---

#### Priority

Until decision about moving it to v0.3.0 prio is low

---

#### Is there possible contributor who could fix the issue

Not decided yet. Maybe both me and Jaroslaw Wiosna

---

**Comment by kermit10000000** [comment]
There are some basic ideas about it https://github.com/JaroslawWiosna/regionalizer/tree/travis_clang but this has to be finished.

**Comment by kermit10000000** [comment]
Part of 0.4.0 release.

**Comment by JaroslawWiosna** [comment]
Starting from scratch with 7e13971
