### ISSUE TITLE
divide/separate methods to the smaller ones. 

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#79]
#### Descrpition

divide/separate methods to the smaller ones. 

--- 

#### Release affected

Not affected as the person who change the code will be obligated to make sure the whole usage of the code he change won't affect the functionality.
Also the person is obligated to make sure everyone commiting will know about that happening.

---

#### Priority

In teory it would be VERY HIGH PRIO as it might affect other peoples work but as it is up the person is obligated to inform and fix all he might destroy in functionality it is low prio.

---

#### Is there possible contributor who could fix the issue

Not decided yet

---

**Comment by kermit10000000** [comment]
Do we need this or maybe it is cool as it is since we can actually test everything(or almost everything)?

**Comment by JaroslawWiosna** [comment]
I am closing it
