### ISSUE TITLE
size of dots on gnuplot map

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#80]
#### Descrpition

the size of City dots in population map should be proportionally big to their population (looks simillar that show heights)

--- 

#### Release affected

v0.3.0 not affected, maybe it will be done additionally or as a part of another realese

---

#### Priority

LOW PRIO- not planned for v0.3.0 and it is side task

---

#### Is there possible contributor who could fix the issue

to be found

---

**Comment by JaroslawWiosna** [comment]
not relevant anymore
