### ISSUE TITLE
bigger database

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#86]
#### Descrpition

database files for new countries. How many and which one is not decided so I assume that about this will mostly decide how many we will be able to get easiely.

--- 

#### Release affected

Yes, It is part of 0.4.0 release.

---

#### Priority

Medium task - Part of the next release. Maybe it will be used by newly introduced class but this two tasks can be separated for now.

---

#### Is there possible contributor who could fix the issue

Wojciech Mielczarek 

---

**Comment by JaroslawWiosna** [comment]
Starting from scratch with 7e13971
