### ISSUE TITLE
refactoring: region class

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#87]
#### Descrpition

New class will be introduced. More information will be provided by the contributor.

--- 

#### Release affected

Yes, it is part of 0.4.0 release

---

#### Priority

Medium Prio - part of the new release. Not affecting other contributors work but as always if something won't work the person who made the change will fix them.

---

#### Is there possible contributor who could fix the issue

Jaroslaw Wiosna

---

**Comment by kermit10000000** [comment]
closed by https://github.com/JaroslawWiosna/regionalizer/pull/88#pullrequestreview-74252830

**Comment by JaroslawWiosna** [comment]
It is not fully done yet.
I am moving it to ONGOING, because I need to improve it.

**Comment by JaroslawWiosna** [comment]
@kermit10000000 I think I am closing the issue this evening.
