### ISSUE TITLE
submodule on wiki

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#92]
#### Descrpition

Wiki page about submodules from our experience, prons, cons, possible problems and solutions. 

--- 

#### Release affected

Yes, it is part of 0.4.0 release.

---

#### Priority

Medium Prio - part of 0.4.0 release, no impact on other contributors work

---

#### Is there possible contributor who could fix the issue

Jaroslaw Wiosna

---

**Comment by kermit10000000** [comment]
what is the status of this task? do we have a DoD for this task?

**Comment by kermit10000000** [comment]
@JaroslawWiosna

**Comment by JaroslawWiosna** [comment]
https://github.com/JaroslawWiosna/regionalizer/wiki/submodules
