### ISSUE TITLE
change usage of ClosestCity

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#94]
#### Descrpition

Make better use out of it than hard-coded Poddebice (that are just to prove it works)

--- 

#### Release affected

Yes it is part of 0.4.0 release but it is blocked( @JaroslawWiosna  could you please comment when it will be possible ? )

---

#### Priority

Medium Prio - part of 0.4.0 release, no impact on other contributors work

---

#### Is there possible contributor who could fix the issue

Wojciech Mielczarek

---

**Comment by JaroslawWiosna** [comment]
@kermit10000000 It will be possible when #87 is closed

**Comment by JaroslawWiosna** [comment]
#87 closed, so this task is not blocked anymore.

**Comment by kermit10000000** [comment]
based on the console output do you have any idea where should we put the call of this function?

**Comment by JaroslawWiosna** [comment]
hmm..., just put it below the name of the `new elected capital`
Like:
```
The best capital: Poddebice
which is near Zgierz->Lodz->Warszawa
```
Please, take care of this task ASAP

**Comment by kermit10000000** [comment]
is this acceptable:            
`
 std::cout << "Which is near: " << ClosestCity::getAllBiggestCitiesInOrder(DatabaseReader::readCitiesFromFile("../database/cities_data"),subregion.getCapital()) << std::endl;`

Or should it be hidden inside of some method or something?

**Comment by kermit10000000** [comment]
Current look:
![obraz](https://user-images.githubusercontent.com/24940166/33040300-edbe1e16-ce3a-11e7-87fb-8e3047b2a6d2.png)

**Comment by kermit10000000** [comment]
Second look:
![obraz](https://user-images.githubusercontent.com/24940166/33040376-26cc7978-ce3b-11e7-90c8-ca64cd5dadf4.png)
+ faster since we avoid getting the same whole vector x times

**Comment by kermit10000000** [comment]
I am also not sure about "which is near" . It looks like this: lodz: which is near Lodz... cos tam(w sensie zdoublowane dziwnie wyglada):
![obraz](https://user-images.githubusercontent.com/24940166/33040493-89d2fd3a-ce3b-11e7-866c-f6f8096f93df.png)

**Comment by kermit10000000** [comment]
Task will be moved to done but it might be improved when the change from fx will be done

**Comment by JaroslawWiosna** [comment]
Starting from scratch with 7e13971
